version: '3.1'

services:
  api:
    image: denoland/deno:latest
    command: run --allow-all /app/app.ts
    volumes: 
      - "./api:/app"
    ports: 
      - 8085:8085

  web:
    image: nginx
    volumes:
     - ./web:/usr/share/nginx/html
    network_mode: host
    environment:
      NGINX_HOST: foobar.com
      NGINX_PORT: 80

  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: sensor
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db: