esphome:
  name: sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: Jadson
  password: "123456789"

web_server:
  port: 80

logger: 

http_request:
  useragent: esphome/device
  timeout: 10s


switch:
  - platform: gpio    
    name: led
    id: led   
    pin:
      number: D5
      mode: OUTPUT
      inverted: True


script:
  - id: service 
    mode: restart
    then:
      - switch.turn_on: led
      - delay: 6s
      - switch.turn_off: led


binary_sensor:
  - platform: gpio
    name: Sensor Movimento   
    pin:
      number: D6
      mode: INPUT
    on_press:
      then: 
        - script.execute: service
        - http_request.post:
              url: https://192.168.0.1:8085/sensor/insert
              headers:
                Content-Type: application/json
              json: |-
                root["sensor_name"] = "Senac Florianópolis / Sala 201";
              verify_ssl: false
